CREATE TABLE tblGenre (
genreID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
genreName VARCHAR(256) NOT NULL,
genreDesc VARCHAR(4096) NULL
)

CREATE TABLE tblBook (
bookID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
bookTitle VARCHAR(256) NOT NULL,
bookPrice SMALLMONEY NULL,
bookDesc VARCHAR(4096) NULL,
genreID INT FOREIGN KEY REFERENCES tblGenre(genreID)
)